<?php if (!defined('APPLICATION')) exit();
/** This file was generated by the Locale Developer plugin on 2010-11-23 12:22:01 **/


$Definition['%s and you'] = '%s and you';
$Definition['%s comment'] = '%s සාකච්චාවන්';
$Definition['%s comments'] = '%s අදහස්';
$Definition['%s Connect'] = '%s Connect';
$Definition['%s message'] = '%s පණිවිඩ';
$Definition['%s New'] = '%s New';
$Definition['%s new'] = '%s new';
$Definition['%s New Plural'] = '%s New';

$Definition['1 message'] = '1 පණිවිඩ';

$Definition['About'] = 'සාමාජික තොරතුරු';
$Definition['Accepted'] = 'පිළිගත්තා';
$Definition['Activity'] = 'ක්‍රියාකාරකම්';
$Definition['Activity.AboutUpdate.FullHeadline'] = '%1$s updated %6$s profile.';
$Definition['Activity.AboutUpdate.ProfileHeadline'] = '%1$s updated %6$s profile.';
$Definition['Activity.ActivityComment.FullHeadline'] = '%1$s commented on %4$s %8$s.';
$Definition['Activity.ActivityComment.ProfileHeadline'] = '%1$s';
$Definition['Activity.AddedToConversation.FullHeadline'] = '%1$s added you to a %8$s.';
$Definition['Activity.AddedToConversation.ProfileHeadline'] = '%1$s added  you to a %8$s.';
$Definition['Activity.BookmarkComment.FullHeadline'] = '%1$s විසින් %8$s ලිපියට අදහසක් එක්කර ඇත.';
$Definition['Activity.BookmarkComment.ProfileHeadline'] = '%1$s විසින් %8$s ලිපියට අදහසක් එක්කර ඇත..';
$Definition['Activity.Comment'] = 'ඔබේ අදහස් දක්වන්න';
$Definition['Activity.CommentMention.FullHeadline'] = '%1$s විසින් %8$s එකකදී %3$s ගැන කතා කර ඇත. ';
$Definition['Activity.CommentMention.ProfileHeadline'] = '%1$s විසින් %8$s එකකදී %3$s ගැන කතා කර ඇත.';
$Definition['Activity.ConversationMessage.FullHeadline'] = '%1$s විසින් ඔබට %8$s එකක් එවා ඇත.';
$Definition['Activity.ConversationMessage.ProfileHeadline'] = '%1$s විසින් ඔබට %8$s එකක් එවා ඇත.';
$Definition['Activity.DiscussionComment.FullHeadline'] = '%1$s විසින් %4$s %8$s එකට අදහස් එක්කර ඇත.';
$Definition['Activity.DiscussionComment.ProfileHeadline'] = '%1$s විසින් %4$s %8$s එකට අදහස් එක්කර ඇත.';
$Definition['Activity.DiscussionMention.FullHeadline'] = '%1$s විසින් %3$s එකකදී  %8$s ගැන කතා කර ඇත.';
$Definition['Activity.DiscussionMention.ProfileHeadline'] = '%1$s විසින් %3$s එකකදී %8$s ගැන කතා කර ඇත.';
$Definition['Activity.Import.FullHeadline'] = '%1$s imported data.';
$Definition['Activity.Import.ProfileHeadline'] = '%1$s imported data.';
$Definition['Activity.Join.FullHeadline'] = '%1$s මෙතැන් සිට helper කෙනෙකි.';
$Definition['Activity.Join.ProfileHeadline'] = '%1$s joined.';
$Definition['Activity.JoinApproved.FullHeadline'] = '%1$s approved %4$s membership application.';
$Definition['Activity.JoinApproved.ProfileHeadline'] = '%1$s approved %4$s membership application.';
$Definition['Activity.JoinCreated.FullHeadline'] = '%3$s created an account for %1$s.';
$Definition['Activity.JoinCreated.ProfileHeadline'] = '%3$s created an account for %1$s.';
$Definition['Activity.JoinInvite.FullHeadline'] = '%1$s accepted %4$s invitation for membership.';
$Definition['Activity.JoinInvite.ProfileHeadline'] = '%1$s accepted %4$s invitation for membership.';
$Definition['Activity.NewDiscussion.FullHeadline'] = '%1$s විසින් discussion එකක් ආරම්භකර ඇත.';
$Definition['Activity.NewDiscussion.ProfileHeadline'] = '%1$s started a %8$s.';
$Definition['Activity.PictureChange.FullHeadline'] = '%1$s පිංතූරය මාරුකරන ලදී.';
$Definition['Activity.PictureChange.ProfileHeadline'] = '%1$s පිංතූරය මාරුකරන ලදී.';
$Definition['Activity.RoleChange.FullHeadline'] = '%1$s changed %4$s permissions.';
$Definition['Activity.RoleChange.ProfileHeadline'] = '%1$s changed %4$s permissions.';
$Definition['Activity.SignIn.FullHeadline'] = '%1$s ඇතුළු වන්න.';
$Definition['Activity.SignIn.ProfileHeadline'] = '%1$s ඇතුළු වන්න.';
$Definition['Activity.WallComment.FullHeadline'] = '%1$s wrote on %4$s %5$s.';
$Definition['Activity.WallComment.ProfileHeadline'] = '%1$s wrote:';
$Definition['Add'] = 'එකතු කරන්න';
$Definition['Add a Comment'] = 'ඔබගේ අදහසත් දැන්ම එකතු කරන්න ';
$Definition['Add Info &amp; Create Account'] = 'Add Info &amp; Create Account';
$Definition['Add Message'] = 'Add Message';
$Definition['Add People to this Conversation'] = 'සංවාදයට තවත් අය එකතු කරගන්න';
$Definition['All Conversations'] = 'All Conversations';
$Definition['All Discussions'] = 'සියලුම සාකච්චාවන්';
$Definition['Allow other members to see your email?'] = 'Allow other members to see your email?';
$Definition['Announce'] = 'Announce';
$Definition['Applicants'] = 'Applicants';
$Definition['Apply'] = 'Apply';
$Definition['Apply for Membership'] = 'රෙජිස්ටර් වෙන්න';
$Definition['Are you sure you want to do that?'] = 'Are you sure you want to do that?';
$Definition['at'] = 'at';

$Definition['Back to Discussions'] = 'Back to Discussions';
$Definition['Bookmark'] = 'Bookmark';
$Definition['bookmarked discussion'] = 'bookmarked discussion';
$Definition['Bookmarked Discussions'] = 'මතක තබාගත් ලිපි';
$Definition['By uploading a file you certify that you have the right to distribute this picture and that it does not violate the Terms of Service.'] = 'ඔබ එකතු කරන පිංතූර සභ්‍ය සහ නීති විරෝධී නොවන පිංතූරයක්ම වීමට වගබලාගන්න.';

$Definition['Cancel'] = 'අහෝසි කරන්න (cancle)';
$Definition['Categories'] = 'Categories';
$Definition['Category'] = 'Category';
$Definition['Change My Password'] = 'මගේ Password එක මාරු කරන්න';
$Definition['Change My Picture'] = 'මගේ පිංතූරය මාරු කරන්න';
$Definition['Close'] = 'Close';
$Definition['comment'] = 'අදහස්';
$Definition['Comment'] = 'අදහස්';
$Definition['Confirm'] = 'අනුමත කරන්න';
$Definition['Confirm Password'] = 'මුරපදය තහවුරු කරන්න';
$Definition['Connect'] = 'Connect';
$Definition['conversation'] = 'conversation';
$Definition['Conversations'] = 'Conversations';
$Definition['Create One.'] = 'දැන්ම ලියාපදිංචි වන්න.';

$Definition['Dashboard'] = 'Dashboard';
$Definition['Date.DefaultDayFormat'] = '%B %e';
$Definition['Date.DefaultFormat'] = '%B %e, %Y';
$Definition['Date.DefaultTimeFormat'] = '%l:%M%p';
$Definition['Date.DefaultYearFormat'] = '%B %Y';
$Definition['Delete'] = 'Delete';
$Definition['Delete Account'] = 'Delete Account';
$Definition['Delete Conversation'] = 'මෙම සංවාදය Delete කරන්න';
$Definition['Delete Discussion'] = 'Delete Discussion';
$Definition['discussion'] = 'සාකච්චාවන්';
$Definition['Discussion Title'] = 'සාකච්චාවේ තේමාව';
$Definition['Discussions'] = 'සාකච්චාවන්';
$Definition['Don\'t have an account? %s'] = 'සාමාජිකයෙක් නොවේද ? %s';
$Definition['dot'] = 'dot';
$Definition['Draft saved at %s'] = 'Draft saved at %s';
$Definition['Drag around and resize the square below to define your thumbnail icon.'] = 'Drag around and resize the square below to define your thumbnail icon.';

$Definition['Edit'] = 'Edit';
$Definition['Edit Account'] = 'Edit Account';
$Definition['Edit My Account'] = 'මගේ ගිණුම වෙනස් කරන්න';
$Definition['Edit My Thumbnail'] = 'මගේ පිංතූරයේ පෙනුම වෙනස් කරන්න';
$Definition['Edit Preferences'] = 'ඉක්මන් දැනුම් දීම් වෙනස් කිරීම්';
$Definition['Email'] = 'විද්‍යුත් ලිපිනය';
$Definition['Email Notifications'] = 'Email Notifications';
$Definition['Email Unavailable'] = 'Email Unavailable';
$Definition['EmailInvitation'] = 'Hello!

%1$s has invited you to join %2$s. If you want to join, you can do so by clicking this link:

  %3$s

Have a great day!';
$Definition['EmailMembershipApproved'] = 'Hello %1$s,

You have been approved for membership. Sign in now at the following link:

 %2$s
  
Have a great day!';
$Definition['EmailNotification'] = '%1$s

Follow the link below to check it out:
%2$s

Have a great day!';
$Definition['EmailPassword'] = 'Hello %1$s,

%2$s has reset your password at %3$s. Your login credentials are now:

  Email: %6$s
  Password: %5$s
  Url: %4$s

Have a great day!';
$Definition['EmailStoryNotification'] = '%1$s

%3$s

---
Follow the link below to check it out:
%2$s

Have a great day!';
$Definition['EmailWelcome'] = 'Hello %1$s,

%2$s has created an account for you at %3$s. Your login credentials are:

  Email: %6$s
  Password: %5$s
  Url: %4$s

Have a great day!';
$Definition['EmailWelcomeConnect'] = 'Hello {User.Name},

You have successfully connected to {Title}. Here is your information:

  Username: {User.Name}
  Connected With: {ProviderName}

You can access the site at {/,url,domain}.

Have a great day!';
$Definition['EmailWelcomeRegister'] = 'Hello {User.Name},

මෙතනින් ඔබට ෆෝරමය නිරීක්ෂණය කල හැක. {/,url,domain}

ඔබ සමූහයේ සාමාජිකයකු වී ඔබගේ වටිනා දැනුම අප සමග බෙදා-හදා ගැනීමට කාරුණික වීම ගැන අපි ඉතාම සතුටු වන්නෙමු.
ක්‍රියාකාරී සාමාජිකයෙක් වශයෙන් කටයුතු කිරීමට පෙර ඔබගේ ඊ-මේල් ගිනුමේ වලංගු භාවය පරීක්ෂා කිරීමට කරුණාකර පහත ලින්ක් එක ක්ලික් කරන්න: ';
$Definition['Enter the email address of the person you would like to invite:'] = 'Enter the email address of the person you would like to invite:';
$Definition['Enter your Email address'] = 'Enter your Email address';
$Definition['Enter your existing account password.'] = 'Enter your existing account password.';
$Definition['ErrorCredentials'] = 'Sorry, no account could be found related to the email and password you entered.';
$Definition['ErrorPermission'] = 'Sorry, permission denied.';
$Definition['ErrorRecordNotFound'] = 'The requested record could not be found.';
$Definition['ErrorTermsOfService'] = 'You must agree to the terms of service.';

$Definition['Female'] = 'ගැහැණු';
$Definition['Forgot?'] = 'අමතකද ?';

$Definition['Gender'] = 'ස්ත්‍රී/පරුෂ';
$Definition['GenderSuffix.First.f'] = '';
$Definition['GenderSuffix.First.m'] = '';
$Definition['GenderSuffix.Third.f'] = '';
$Definition['GenderSuffix.Third.m'] = '';
$Definition['Go'] = 'Go';
$Definition['GuestModule.Message'] = '<p>▪ අන්තර්ජාලයේ මුදල් ඉපයීම <br/>▪ තාක්‍ෂණික ගැටළු <br/>▪ එදිනෙදා ජිවිතයේ පැන නගින ගැටළු <br/>▪ අධ්‍යාපනික ගැටළු ආදී ඕනෑම ගැටලුවකට <br/>▪ පිළිතුරු දැන් පහසුවෙන් සිංහලෙන්ම.<br/>▪ ඔබත් දැන්ම එකතුවන්න, අන් අය සමග දැනුම බෙදාගන්න.</p>';

$Definition['he'] = 'he';
$Definition['her'] = 'her';
$Definition['his'] = 'his';
$Definition['Howdy, Stranger!'] = 'ඔබ තවමත් සාමාජිකයෙක්  වුණේ නැත්ද ?
 ?';

$Definition['I agree to the <a id="TermsOfService" class="Popup" target="terms" href="%s">terms of service</a>'] = 'I agree to the <a id="TermsOfService" class="Popup" target="terms" href="%s">terms of service</a>';
$Definition['I remember now!'] = 'මාගේ ඇතුල්වීම මතක තබාගන්න!';
$Definition['In this Conversation'] = 'මෙම සංවාදයට එකතු වූ අය';
$Definition['Inbox'] = 'පණිවිඩ';
$Definition['Internal'] = 'Internal';
$Definition['Invitation Code'] = 'Invitation Code';
$Definition['Invite'] = 'Invite';
$Definition['Invited by'] = 'Invited by';

$Definition['Joined'] = 'එක්වූයේ';

$Definition['Keep me signed in'] = 'ඇතුලුවීම මතක තබාගන්න';

$Definition['Last Active'] = 'අවසන් පැමිණීම';
$Definition['Login with Facebook'] = 'Login with Facebook';

$Definition['Male'] = 'පිරිමි';
$Definition['Most recent by %1$s'] = 'අවසාන අදහස  %1$s';
$Definition['My Bookmarks'] = 'මතක තබාගත් ලිපි';
$Definition['My Discussions'] = 'මගේ ලිපි';
$Definition['My Drafts'] = 'ලියමින් පවතින ලිපි';
$Definition['My Invitations'] = 'My Invitations';
$Definition['My Preferences'] = 'ඉක්මන් දැනුම් දීම් වෙනස් කිරීම්';

$Definition['Name Unavailable'] = 'Name Unavailable';
$Definition['No discussions were found.'] = 'No discussions were found.';
$Definition['Notifications'] = 'දැනුම්දීම්';
$Definition['Notify me of private messages.'] = 'මට ලැඛෙන පෞද්ගලික පණිවිඩ පිළිබද දැනුම් දෙන්න.';
$Definition['Notify me when I am added to private conversations.'] = 'පෞද්ගලික සංවාදයකට මාව එකතුකරගත් විට සැනුම් දෙන්න.';
$Definition['Notify me when people comment on my bookmarked discussions.'] = 'මම bookmark කළ ලිපිවලට කෙනෙකු අදහස් දැක්වූවොත් ඒ බව දැනුම් දෙන්න.';
$Definition['Notify me when people comment on my discussions.'] = 'මගේ ලිපියකට වෙනත් අයෙකු අදහස් දැක්වූවොත් ඒ බව දැනුම් දෙන්න.';
$Definition['Notify me when people mention me in comments.'] = 'සංවාදයකදී කෙනෙකු මම ගැන කතා කළහොත් ඒ බව මට දැනුම් දෙන්න.';
$Definition['Notify me when people mention me in discussion titles.'] = 'සංවාද මාතෘකාවකදී කෙනෙකු මම ගැන කතා කළහොත් ඒ බව මට දැනුම් දෙන්න.';
$Definition['Notify me when people reply to my wall comments.'] = 'මගේ වෝල් එකේ ඇති දේවල් වලට ලැඛෙන ප්‍රථිචාර දැනුම් දෙන්න.';
$Definition['Notify me when people write on my wall.'] = 'වෙනත් කෙනෙකු මගේ වෝල් එකේ ලිවූ විට දැනුම් දෙන්න.';

$Definition['Okay'] = 'Okay';
$Definition['On'] = 'On';
$Definition['Options'] = 'Options';
$Definition['Or you can...'] = 'Or you can...';
$Definition['Original'] = 'Original';

$Definition['PageDetailsMessage'] = '%1$s to %2$s';
$Definition['PageDetailsMessageFull'] = '%1$s to %2$s of %3$s';
$Definition['Password'] = 'Password';
$Definition['PasswordRequest'] = 'Hello %1$s,

Someone has requested to reset your password at %2$s. To reset your password, follow this link:

  %3$s

If you did not make this request, disregard this email.';
$Definition['Passwords don\'t match'] = 'Passwords don\'t match';
$Definition['Permalink'] = 'Permalink';
$Definition['Please wait while you are redirected. If you are not redirected, click <a href="%s">here</a>.'] = 'Please wait while you are redirected. If you are not redirected, click <a href="%s">here</a>.';
$Definition['Post Comment'] = 'අදහස එකතු කරන්න';
$Definition['Post Discussion'] = 'සාකච්චාවක් අරබන්න';
$Definition['Powered by Vanilla'] = 'Powered by Vanilla';
$Definition['Preview'] = 'Preview';
$Definition['Profile Picture'] = 'Profile Picture';

$Definition['Recent Activity'] = 'නවතම ක්‍රියාකාරකම්';
$Definition['Recipients'] = 'Recipients';
$Definition['Redirecting...'] = 'Redirecting...';
$Definition['Remember me on this computer'] = 'මාගේ ඇතුල්වීම මතක තබාගන්න.';
$Definition['Remove My Picture'] = 'මගේ පිංතූරය ඉවත් කරන්න';
$Definition['Request a new password'] = 'Request a new password';
$Definition['Roles'] = 'තත්වය';

$Definition['Save'] = 'Save';
$Definition['Save Draft'] = 'Save Draft';
$Definition['Save Preferences'] = 'Save Preferences';
$Definition['Search'] = 'සොයන්න';
$Definition['Select an image on your computer (2mb max)'] = 'ඔබේ පරිගණකයේ ඇති පිංතූරයක් තෝරන්න (පිංතූරය 2 MB ට අඩු විය යුතුයි)';
$Definition['Send %s a Message'] = '%sට පණිවිඩයක් යවන්න';
$Definition['Send Message'] = 'පණිවිඩයක් යවන්න';
$Definition['Sent To'] = 'Sent To';
$Definition['Share'] = 'යොමු කරන්න';
$Definition['she'] = 'ඇය';
$Definition['Sign In'] = 'ඇතුළු වන්න';
$Definition['Sign In with Google'] = 'Sign In with Google';
$Definition['Sign In with OpenID'] = 'Sign In with OpenID';
$Definition['Sign In with Twitter'] = 'Sign In with Twitter';
$Definition['Sign Out'] = 'පිටවීම';
$Definition['Sign Up'] = 'සාමාජිකයෙක් වන්න';
$Definition['Sink'] = 'Sink';
$Definition['somebody'] = 'somebody';
$Definition['Start a New Conversation'] = 'පෞද්ගලික පණිවුඩයක් ආරම්භ කරන්න';
$Definition['Start a New Discussion'] = 'සාකච්චාවක් ආරම්භ කරන්න';
$Definition['Start Conversation'] = 'සංවාදයක් අරබන්න';
$Definition['Started by %1$s'] = 'ආරම්බ කලේ %1$s';
$Definition['Status'] = 'Status';

$Definition['Thank You!'] = 'Thank You!';
$Definition['Thumbnail'] = 'Thumbnail';
$Definition['Transport error: %s'] = 'A fatal error occurred while processing the request.<br />The server returned the following response: %s';

$Definition['Unbookmark'] = 'Unbookmark';
$Definition['Upload'] = 'Upload';
$Definition['Username'] = 'Username';

$Definition['ValidateBoolean'] = '%s is not a valid boolean.';
$Definition['ValidateConnection'] = 'The connection parameters you specified failed to open a connection to the database. The database reported the following error: <code>%s</code>';
$Definition['ValidateDate'] = '%s is not a valid date.';
$Definition['ValidateDecimal'] = '%s is not a valid decimal.';
$Definition['ValidateEmail'] = '%s does not appear to be valid.';
$Definition['ValidateEnum'] = '%s is not valid.';
$Definition['ValidateInteger'] = '%s is not a valid integer.';
$Definition['ValidateLength'] = '%1$s is %2$s characters too long.';
$Definition['ValidateMatch'] = 'The %s fields do not match.';
$Definition['ValidateMinimumAge'] = 'You must be at least 16 years old to proceed.';
$Definition['ValidateOneOrMoreArrayItemRequired'] = 'You must select at least one %s.';
$Definition['ValidateRegex'] = '%s does not appear to be in the correct format.';
$Definition['ValidateRequired'] = '%s is required.';
$Definition['ValidateRequiredArray'] = 'You must select at least one %s.';
$Definition['ValidateTime'] = '%s is not a valid time.';
$Definition['ValidateTimestamp'] = '%s is not a valid timestamp.';
$Definition['ValidateUsername'] = 'Usernames must be 3-20 characters and consist of letters, numbers, and underscores.';
$Definition['ValidateVersion'] = 'The %s field is not a valid version number. See the php version_compare() function for examples of valid version numbers.';
$Definition['Visits'] = 'පැමිණීම්';

$Definition['wall'] = 'wall';
$Definition['Why do you want to join?'] = 'Why do you want to join?';
$Definition['Write a comment'] = 'ඔබේ අදහස් දක්වන්න';
$Definition['Write Comment'] = 'අදහසක් දක්වන්න';
$Definition['Write something about yourself...'] = 'Write something about yourself...';

$Definition['you'] = 'ඔබ';
$Definition['You'] = 'ඔබ';
$Definition['You already have an account here.'] = 'You already have an account here.';
$Definition['You are connected as %s through %s.'] = 'You are connected as %s through %s.';
$Definition['You do not have any conversations.'] = 'ඔබ දැනට පෞද්ගලික සාකච්ඡාවක් ආරම්භ කර නැත.';
$Definition['You do not have any notifications yet.'] = 'ඔබට කිසිම දැනුම් දීමක් නොමැත.';
$Definition['your'] = 'ඔබේ';
$Definition['Your application will be reviewed by an administrator. You will be notified by email if your application is approved.'] = 'Your application will be reviewed by an administrator. You will be notified by email if your application is approved.';
$Definition['Your registered username: <strong>%s</strong>'] = 'Your registered username: <strong>%s</strong>';


$Definition['Comments']= 'අදහස්';
$Definition['Closed']= 'වසා දමන ලදී';
$Definition['Announcement'] = 'විශේෂ දැනුම්දීමයි';
$Definition['This discussion has been closed.'] = 'කණගාටුයි, මෙම සාකච්චාව වසා දමා ඇත..';

